CREATE TABLE IF NOT EXISTS users (
    id bigserial PRIMARY KEY,  
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp(0) with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp(0) with time zone NOT NULL DEFAULT NOW(),
    deleted_at timestamp(0) with time zone,
    first_name text NOT NULL,
    last_name text NOT NULL,
    dob date,
    sex text,
    username text NOT NULL UNIQUE,
    email text NOT NULL,
    password text NOT NULL,
    avatar text,
    club_id bigint,
    club_role_id bigint,
    about_me text,
    elo_fide integer NOT NULL DEFAULT 1200,
    elo_national integer NOT NULL DEFAULT 1200,
    elo_regional integer NOT NULL DEFAULT 1200,
    chess_com_username text,
    lichess_username text,
    chess24_username text,
    country text NOT NULL DEFAULT 'SPAIN',
    province text,
    city text,
    neighborhood text,
    CONSTRAINT fk_club_id
        FOREIGN KEY (club_id)
            REFERENCES clubs(club_id)
);
