CREATE TABLE IF NOT EXISTS users (
    user_id bigserial PRIMARY KEY,
    is_active boolean NOT NULL DEFAULT FALSE,
    is_verified boolean NOT NULL DEFAULT FALSE,
    is_admin_of_club boolean NOT NULL DEFAULT FALSE,
    club_admin_of bigint NOT NULL DEFAULT 0, -- fk to club
    created_at timestamp(0) with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp(0) with time zone NOT NULL DEFAULT NOW(),
    soft_deleted bool NOT NULL DEFAULT FALSE,
    first_name text NOT NULL DEFAULT '',
    last_name text NOT NULL DEFAULT '',
    dob date NOT NULL DEFAULT '1900-01-01',
    chess_age_category text NOT NULL DEFAULT '',
    sex text NOT NULL DEFAULT '',
    username text NOT NULL DEFAULT '',
    email text NOT NULL DEFAULT '',
    password text NOT NULL DEFAULT '',
    password_reset_token text NOT NULL DEFAULT '',
    avatar text NOT NULL DEFAULT '',
    club_id bigint NOT NULL DEFAULT '', -- fk to club membership
    club_role_id bigint NOT NULL DEFAULT '', -- fk to club_roles
    user_code text NOT NULL DEFAULT uuid_generate_v1(),
    about_me text NOT NULL DEFAULT '',
    elo_fide_standard integer NOT NULL DEFAULT 1200,
    elo_fide_rapid integer NOT NULL DEFAULT 1200,
    elo_fide_blitz integer NOT NULL DEFAULT 1200,
    elo_fide_lightning integer NOT NULL DEFAULT 1200,

    elo_national_standard integer NOT NULL DEFAULT 1200,
    elo_national_rapid integer NOT NULL DEFAULT 1200,
    elo_national_blitz integer NOT NULL DEFAULT 1200,
    elo_national_lightning integer NOT NULL DEFAULT 1200,

    elo_regional_standard integer NOT NULL DEFAULT 1200,
    elo_regional_rapid integer NOT NULL DEFAULT 1200,
    elo_regional_blitz integer NOT NULL DEFAULT 1200,
    elo_regional_lightning integer NOT NULL DEFAULT 1200,

    is_arbiter boolean NOT NULL DEFAULT FALSE,
    is_coach boolean NOT NULL DEFAULT FALSE,
    price_per_hour integer NOT NULL DEFAULT 0,
    chess_com_username text NOT NULL DEFAULT '',
    lichess_username text NOT NULL DEFAULT '',
    chess24_username text NOT NULL DEFAULT '',
    country text NOT NULL DEFAULT '',
    province text NOT NULL DEFAULT '',
    city text NOT NULL DEFAULT '',
    neighborhood text NOT NULL DEFAULT '',
    version integer NOT NULL DEFAULT 0
);
