CREATE TABLE IF NOT EXISTS clubs (
    club_id bigserial PRIMARY KEY,  
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp(0) with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp(0) with time zone NOT NULL DEFAULT NOW(),
    deleted_at timestamp(0) with time zone,
    name text NOT NULL,
    description text,
    avatar text,
    organizer_id bigint,
    email text NOT NULL,
    phone text,
    website text,
    country text NOT NULL DEFAULT 'SPAIN',
    province text,
    city text,
    address text,
    members integer[] NOT NULL DEFAULT '{}',
);
