CREATE TABLE IF NOT EXISTS users (
    user_id bigserial PRIMARY KEY,
    is_active boolean NOT NULL DEFAULT FALSE,
    is_verified boolean NOT NULL DEFAULT FALSE,
    is_admin_of_club boolean NOT NULL DEFAULT FALSE,
    club_admin_of bigint, -- fk to club
    created_at timestamp(0) with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp(0) with time zone NOT NULL DEFAULT NOW(),
    deleted_at timestamp(0) with time zone,
    first_name text NOT NULL,
    last_name text NOT NULL,
    dob date,
    sex text,
    username text,
    email text,
    password text,
    password_reset_token text,
    avatar text,
    club_id bigint, -- fk to club membership
    club_role_id bigint, -- fk to club_roles
    about_me text,
    elo_fide integer NOT NULL DEFAULT 1200,
    elo_national integer NOT NULL DEFAULT 1200,
    elo_regional integer NOT NULL DEFAULT 1200,
    is_arbiter boolean NOT NULL DEFAULT FALSE,
    is_coach boolean NOT NULL DEFAULT FALSE,
    price_per_hour integer NOT NULL DEFAULT 0,
    chess_com_username text NOT NULL DEFAULT '',
    lichess_username text NOT NULL DEFAULT '',
    chess24_username text NOT NULL DEFAULT '',
    country text NOT NULL DEFAULT 'SPAIN',
    province text NOT NULL DEFAULT '',
    city text NOT NULL DEFAULT '',
    neighborhood text NOT NULL DEFAULT ''
);
